set_property PACKAGE_PIN AC19 [get_ports clock]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets clock]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clock]

set_property PACKAGE_PIN Y3 [get_ports reset]

set_property PACKAGE_PIN K23 [get_ports {led_controller[0]}]
set_property PACKAGE_PIN J21 [get_ports {led_controller[1]}]
set_property PACKAGE_PIN H23 [get_ports {led_controller[2]}]
set_property PACKAGE_PIN J19 [get_ports {led_controller[3]}]
set_property PACKAGE_PIN G9 [get_ports {led_controller[4]}]
set_property PACKAGE_PIN J26 [get_ports {led_controller[5]}]
set_property PACKAGE_PIN J23 [get_ports {led_controller[6]}]
set_property PACKAGE_PIN J8 [get_ports {led_controller[7]}]
set_property PACKAGE_PIN H8 [get_ports {led_controller[8]}]
set_property PACKAGE_PIN G8 [get_ports {led_controller[9]}]
set_property PACKAGE_PIN F7 [get_ports {led_controller[10]}]
set_property PACKAGE_PIN A4 [get_ports {led_controller[11]}]
set_property PACKAGE_PIN A5 [get_ports {led_controller[12]}]
set_property PACKAGE_PIN A3 [get_ports {led_controller[13]}]
set_property PACKAGE_PIN D5 [get_ports {led_controller[14]}]
set_property PACKAGE_PIN H7 [get_ports {led_controller[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports {led_controller[*]}]